### ISSUE TITLE
[Feat] Add DELETE Api for todo creation

### ISSUE THREAD

**Issue by gibeom0218** [slid-todo/front#110]
## ✨ 작업 내용
- [x]  할 일 삭제 api 생성
- [x]  delete 에 관한 커스텀 훅
- [x] 할 일 모달 이미지 처리 수정
- [x] 할 일 데이터 추출 과정 리팩토링
- [x]  test
